### ISSUE TITLE
Tf-agent-token

### ISSUE THREAD

**Issue by agiwalpooja20** [assareh/tfc-agent#12]
Hi @assareh I was trying to use your tfc-agent-ecs code for running agents.
I am not sure why you are not using 
```resource "tfe_agent_token" "test-agent-token" {
  agent_pool_id = tfe_agent_pool.test-agent-pool.id
  description   = "my-agent-token-name"
}
```
https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/agent_token

to create tokens and using instead shell script.
Any particular reason for doing this?

**Comment by assareh** [comment]
thank you @agiwalpooja20 for reaching out! you are correct and i've updated the repo. it was due to neglect :) i had simply forgotten to update the docs after the tfe provider was updated. when i created the repo originally those resources were not available.
