### ISSUE TITLE
ECS container exits after task

### ISSUE THREAD

**Issue by geofflancaster** [assareh/tfc-agent#30]
I'm not using the auto scale up/down functionality but whenever a task completes (success or fail), the agent is exiting. Is this expected behavior?

**Comment by assareh** [comment]
Hi @geofflancaster , yes that is expected. On [this line](https://github.com/assareh/tfc-agent/blob/master/tfc-agent-ecs/producer/main.tf#L53) I have [single execution mode](https://developer.hashicorp.com/terraform/cloud-docs/agents/agents#optional-configuration-single-execution-mode) enabled. This ensures that the agent only runs a single workload, then terminates. You can use this configuration in combination with Docker and a process supervisor to ensure a clean working environment for every Terraform run.
